// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JCTBJtyDRCv7gC2D17VForIzyYAXUDs',
    appId: '1:949770099373:android:d80e783382136d675d8424',
    messagingSenderId: '949770099373',
    projectId: 'flutter-firebase-7f2fc',
    storageBucket: 'flutter-firebase-7f2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz1Op2PvqcnAlLt5mlohtGrw9uWh515i4',
    appId: '1:949770099373:ios:dc31fda73fde766d5d8424',
    messagingSenderId: '949770099373',
    projectId: 'flutter-firebase-7f2fc',
    storageBucket: 'flutter-firebase-7f2fc.firebasestorage.app',
    androidClientId: '949770099373-3eh15eqdvr97b5qeumoe6ct3kj3r2vj4.apps.googleusercontent.com',
    iosClientId: '949770099373-ngmcfcvkipt9rplp8goqr3h8cqi435t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie2',
  );
}
